### ISSUE TITLE
commit initial code

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/reconciler#1]
@FatimaFawaz can you please commit your current flask app into this repository https://github.com/SSOC18/reconciler/

**Comment by FatimaFawaz** [comment]
Tried to push the changes to the repository and got the error:
remote: Permission to SSOC18/reconciler.git denied to FatimaFawaz.

**Comment by shadiakiki1986** [comment]
Will see what I missed in the repository settings and get back to you

**Comment by shadiakiki1986** [comment]
Please try again now. Btw, you might have received an email invitation too. Please ignore it.

**Comment by FatimaFawaz** [comment]
Done.
