### ISSUE TITLE
simplify app routes (~2h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/reconciler#2]
Let's fix the last issue that you reported about being unable to upload files after a reconciliation.

Modify the 1st route that uploads:
- so that it doesn't execute a reconciliation
- it will just save the files into the `Upload Folder`
- then it uses the new prefix of the files
- and it redirects to the 2nd route of load "previous file" where previous = the current new prefix

Modify the 2nd route that displays previous reconciliations
- add a link that says "upload new reconciliation" that redirects to the previous route

**Comment by FatimaFawaz** [comment]
So I did the modifications but I'm not 100% sure the result matches your specifications. The routes have been modified accordingly, so now the program displays one of two views:
![screen shot 2018-07-20 at 5 54 50 pm](https://user-images.githubusercontent.com/40644150/43009430-58d614fa-8c46-11e8-9d3d-b685e133f8d2.png)
![screen shot 2018-07-20 at 5 54 32 pm](https://user-images.githubusercontent.com/40644150/43009431-58f7f8a4-8c46-11e8-8df5-7c7a37d9a7be.png)

**Comment by shadiakiki1986** [comment]
Yes it matches. You can even split the lis of previous reconciliations to a
3rd route on its own so you end up with 3 short routes instead of long pages

**Comment by FatimaFawaz** [comment]
Modified it: 
![screen shot 2018-07-20 at 7 32 05 pm](https://user-images.githubusercontent.com/40644150/43014123-d5351502-8c53-11e8-8d90-3e3a38763860.png)
![screen shot 2018-07-20 at 7 32 16 pm](https://user-images.githubusercontent.com/40644150/43014124-d55c2d5e-8c53-11e8-9728-cd9cd96f345c.png)
![screen shot 2018-07-20 at 7 32 11 pm](https://user-images.githubusercontent.com/40644150/43014125-d57ff9fa-8c53-11e8-9829-f5d6c90718b9.png)

**Comment by shadiakiki1986** [comment]
LGTM
