### ISSUE TITLE
read one of the two files from a database instead of upload (~3h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/reconciler#3]
- create a new route in the flask app for the below
- create a database table that will replace one of the uploaded files
    - we will use [postgresql](http://postgresql.org/)
- here's is an example structure:
    - table name: securities
    - fields: symbol, position (like the uploaded files)
- modify the flask app to read one of the files from this database (use pandas [read_sql_table](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html))
- on the `ssoc18.teamshadi.net` server, I already created a database called `mf_dummy`
    - it doesnt have any tables yet (you will need to create one as per the above structure)
    - use `psql mf_dummy` in a terminal (from the jupyter server) to log into postgresql and write SQL commands
    - save your `CREATE TABLE` commands in a file for later reference

**Comment by FatimaFawaz** [comment]
I can't find mf_dummy anywhere on the server

**Comment by FatimaFawaz** [comment]
So far:
- I've created a new route in the flask app to direct to the database upload
- I create a table in the mf_dummy database with the required fields using psql and saved it
- imported sqlalchemy to create an engine and connect to it
- imported the existing database via sqlalchemy (not working)
The issue I have lies with the url parsing and using the correct dialects for postgres. 
I'm still debugging the code while taking away some features to be added later to the upload database route (checking file name if null, checking existence in database)

 The error I get is: 
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'postgres:http://ssoc18.teamshadi.net:8000/mf_dummy'

in regards to the line:
engine = create_engine('postgres:http://ssoc18.teamshadi.net:8000/mf_dummy', echo=True)

**Comment by shadiakiki1986** [comment]
Ok. Can you please commit your code into the repository?

**Comment by FatimaFawaz** [comment]
done

**Comment by shadiakiki1986** [comment]
I fixed a few issues in your code.
You can see them with `git diff .` from the internal `flaskr` folder. 
Here's a summary of the changes
- fixed the sqlalchemy URI
- edited the templates to drop the `http://ssoc18.teamshadi.net:5000` from all URLs in order that I can test the app on port 5002
- fixed your usage of the sqlalchemy engine with pandas `read_sql_table`
- inserted a row into the table `mf_dummy.securities` since it was empty
- added some postprocessing in your  `redux` view

**Comment by shadiakiki1986** [comment]
btw, a few comments
- no need for the user to enter the table name
- add a link "upload from database" when viewing previous reconciliations

Once done, please commit your code so we can move on to the next step

**Comment by shadiakiki1986** [comment]
also, I didn't find the `CREATE TABLE` command you used anywhere in the code. Maybe paste it into the README file

**Comment by FatimaFawaz** [comment]
So I added the link to the database reconciliation from the previous recon view, removed the need to write the table name. 
I didn't use any commands aside from CREATE TABLE to create and modify the table, I went to editor and wrote in all the details from there.

**Comment by shadiakiki1986** [comment]
Here are a few modifications I made this morning to your flask application
- added `settings.py.dist` which is a copy of `settings.py`, except that it 
  - does not contain sensitive information like passwords
  - can be safely committed into the git repo for source control
- the `settings.py.dist` serves as a template for new deployments of your application
- added `settings.py` which contains sensitive information like the database password
  - this file should *not* be committed into the repository
- modified `flaskr.py` to read the `settings.py` file into `app.config` as per the flask docs on [configuration handling](http://flask.pocoo.org/docs/0.12/config/)
- modified the sqlalchemy call that takes in the complete database URI to read it from the `settings.py` file
  - this way, if another deployment has a different username/password/database name/...  , all that is needed is a different variable value in the `settings.py`

Aside from that,
- Where is the link to upload a new `file versus database` reconciliation after seeing the result of the reconciliation? 
- What do you mean by `went to editor and wrote in all the details from there`?
    - do you mean that in the terminal you opened `psql mf_dummy` and wrote your `Create Table` command there?

**Comment by shadiakiki1986** [comment]
btw, please make sure to commit the new edits again into the repository

**Comment by FatimaFawaz** [comment]
I added a link to upload file vs db from the Recon view and I committed the changes to github minus the settings.py file. Yes I opened psql mf_dummy, used the create table command, but I accessed the command line editor of the table after creating it and wrote in the SQL code for it.

**Comment by shadiakiki1986** [comment]
And what was the code you wrote for the table?

**Comment by FatimaFawaz** [comment]
CREATE TABLE securities (
    symbol varchar(255),
    position int
);

**Comment by shadiakiki1986** [comment]
Ok so this should go into the readme please

**Comment by FatimaFawaz** [comment]
I made a separate readme.txt in the Recon folder. Is that alright?
Nevermind, please ignore this...

**Comment by FatimaFawaz** [comment]
Done

**Comment by shadiakiki1986** [comment]
Not really. I suggest you read the git tutorial so that you would
understand how you can improve your usage of git

**Comment by shadiakiki1986** [comment]
I will close this issue and continue the discussion on the pending issues of README in https://github.com/SSOC18/reconciler/issues/4
