### ISSUE TITLE
add "*.csv" to .gitignore

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/reconciler#4]
I noticed that the repository contains all the csv files that we uploaded during testing (e.g. check [here](https://github.com/SSOC18/reconciler/tree/master/Recon/flaskr/flaskr/Upload%20Folder)).
These files do not form part of the application source code and should not be committed into the repository.
Create a `.gitignore` file (more details [here](https://help.github.com/articles/ignoring-files/)) to ignore them and not upload them into the repository.

This [Git tutorial](https://git-scm.com/book/en/v1/Getting-Started) is useful for you since you seem to be new to git

**Comment by FatimaFawaz** [comment]
I had already done these changes before I left but hadn't written them down:
I attempted .gitignore on the initial folder then copied all the files into a new Reconciler folder and committed it and added a new .gitignore with only the .csv files. I still didn't remove the old 'Recon' folder.

**Comment by shadiakiki1986** [comment]
It's really confusing to have 2 folders. Is there anything stopping you from dropping the older `Recon` folder?

**Comment by shadiakiki1986** [comment]
Btw, the csv files are all still there in the upload folder, e.g. check [here](https://github.com/SSOC18/reconciler/tree/master/Reconciler/flaskr/flaskr/Upload_Folder)
