### ISSUE TITLE
application aesthetics (~2h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/reconciler#5]
Let's make the application look nicer by adding a common navigation bar that has the 3 links on top of the page
1. "file versus file" reconciliation
2. "file versus database" reconciliation
3. view previous reconciliations

Also, the readme.txt file currently only has the commands needed to run the application.
It's a good idea to write some prose describing what this application allows the user to do.
Another thing to include is that new deployments of your application requires the installer to
copy the `settings.py.dist` file to `settings.py` and put in the database credentials there

**Comment by FatimaFawaz** [comment]
- Added a working navigation bar to all the .html files
- Created a readme.md file to be found in /Recon/flaskr
- Renamed the readme.txt file in the app directory to run.txt

**Comment by shadiakiki1986** [comment]
I just tried to check this by going to http://ssoc18.teamshadi.net:5002/ but I guess the application is not currently running. Let me know when you launch it again so I can test.
